clean: true
author: Rakuten Group, Inc.
github_url: https://github.com/rakutentech/ios-signatureverifier
module_version: 0.1.0
module: RSignatureVerifier
xcodebuild_arguments:
  - -workspace
  - RSignatureVerifier.xcworkspace
  - -scheme
  - SampleApp
podspec: RSignatureVerifier.podspec
readme: README.md
documentation: "*.md"
hide_documentation_coverage: true
